export default function MainPage () {
  return(
    <>
    <div>SSSSSSfsdfshdfjshfksdhfkasfs
      SSSSSSfsdfshdfjshfksdhfkasfss
      SSSSSSfsdfshdfjshfksdhfkasfs
      SSSSSSfsdfshdfjshfksdhfkasfss
      SSSSSSfsdfshdfjshfksdhfkasfs
      SSSSSSfsdfshdfjshfksdhfkasfss
      SSSSSSfsdfshdfjshfksdhfkasfs
      SSSSSSfsdfshdfjshfksdhfkasfssSSSSSSfsdfshdfjshfksdhfkasfs
      SSSSSSfsdfshdfjshfksdhfkasfssSSSSSSfsdfshdfjshfksdhfkasfs
      SSSSSSfsdfshdfjshfksdhfkasfssSSSSSSfsdfshdfjshfksdhfkasfs
      SSSSSSfsdfshdfjshfksdhfkasfssSSSSSSfsdfshdfjshfksdhfkasfs
      SSSSSSfsdfshdfjshfksdhfkasfssSSSSSSfsdfshdfjshfksdhfkasfs
      SSSSSSfsdfshdfjshfksdhfkasfssSSSSSSfsdfshdfjshfksdhfkasfs
      SSSSSSfsdfshdfjshfksdhfkasfssSSSSSSfsdfshdfjshfksdhfkasfs
      SSSSSSfsdfshdfjshfksdhfkasfssSSSSSSfsdfshdfjshfksdhfkasfs
      SSSSSSfsdfshdfjshfksdhfkasfssSSSSSSfsdfshdfjshfksdhfkasfs
      SSSSSSfsdfshdfjshfksdhfkasfssSSSSSSfsdfshdfjshfksdhfkasfs
      SSSSSSfsdfshdfjshfksdhfkasfssSSSSSSfsdfshdfjshfksdhfkasfs
      SSSSSSfsdfshdfjshfksdhfkasfssSSSSSSfsdfshdfjshfksdhfkasfs
      SSSSSSfsdfshdfjshfksdhfkasfssSSSSSSfsdfshdfjshfksdhfkasfs
      SSSSSSfsdfshdfjshfksdhfkasfssSSSSSSfsdfshdfjshfksdhfkasfs
      SSSSSSfsdfshdfjshfksdhfkasfssSSSSSSfsdfshdfjshfksdhfkasfs
      SSSSSSfsdfshdfjshfksdhfkasfssSSSSSSfsdfshdfjshfksdhfkasfs
      SSSSSSfsdfshdfjshfksdhfkasfssSSSSSSfsdfshdfjshfksdhfkasfs
      SSSSSSfsdfshdfjshfksdhfkasfssSSSSSSfsdfshdfjshfksdhfkasfs
      SSSSSSfsdfshdfjshfksdhfkasfssSSSSSSfsdfshdfjshfksdhfkasfs
      SSSSSSfsdfshdfjshfksdhfkasfssSSSSSSfsdfshdfjshfksdhfkasfs
      SSSSSSfsdfshdfjshfksdhfkasfss
    </div>
    </>
  )
}